USE [dbdf]
GO

/****** Object:  Table [dbo].[CENTER]    Script Date: 01/19/2012 15:39:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CENTER](
	[C_ID] [numeric](18, 0) NOT NULL,
	[DISTINCT_TITLE] [varchar](40) NOT NULL,
	[ADDRESS] [varchar](50) NOT NULL,
	[POSTAL_CODE] [numeric](5, 0) NOT NULL,
	[TEL_NUM] [numeric](14, 0) NOT NULL,
	[CITY] [varchar](20) NOT NULL,
	[HEALTH_SECTOR] [varchar](50) NOT NULL,
	[MUNICIPALITY] [varchar](20) NOT NULL,
 CONSTRAINT [PK_CENTER] PRIMARY KEY CLUSTERED 
(
	[C_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

