USE [dbdf]
GO

/****** Object:  Table [dbo].[EXT_COLAB]    Script Date: 01/19/2012 15:39:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EXT_COLAB](
	[AFM] [bigint] NOT NULL,
	[ID] [char](10) NOT NULL,
	[WORKS_WITH_CENTER] [numeric](18, 0) NULL,
 CONSTRAINT [PK_EXT_COLAB] PRIMARY KEY CLUSTERED 
(
	[AFM] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[EXT_COLAB]  WITH CHECK ADD  CONSTRAINT [FK_EXT_COLAB_CENTER] FOREIGN KEY([WORKS_WITH_CENTER])
REFERENCES [dbo].[CENTER] ([C_ID])
GO

ALTER TABLE [dbo].[EXT_COLAB] CHECK CONSTRAINT [FK_EXT_COLAB_CENTER]
GO

ALTER TABLE [dbo].[EXT_COLAB]  WITH CHECK ADD  CONSTRAINT [FK_EXT_COLAB_EXT_COLAB] FOREIGN KEY([AFM])
REFERENCES [dbo].[EXT_COLAB] ([AFM])
GO

ALTER TABLE [dbo].[EXT_COLAB] CHECK CONSTRAINT [FK_EXT_COLAB_EXT_COLAB]
GO

ALTER TABLE [dbo].[EXT_COLAB]  WITH CHECK ADD  CONSTRAINT [FK_EXT_COLAB_PERSON] FOREIGN KEY([ID])
REFERENCES [dbo].[PERSON] ([ID])
GO

ALTER TABLE [dbo].[EXT_COLAB] CHECK CONSTRAINT [FK_EXT_COLAB_PERSON]
GO

