USE [dbdf]
GO

/****** Object:  Table [dbo].[MEDICAL_TREATMENT]    Script Date: 01/19/2012 15:42:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MEDICAL_TREATMENT](
	[PATIENT_ID] [varchar](10) NOT NULL,
	[TREAT_ID] [int] NOT NULL,
	[LAST_DOSE] [date] NULL,
	[NEXT_DOSE] [date] NULL,
	[QUANTITY] [smallint] NULL,
	[START_DATE] [date] NOT NULL,
	[ID_PAT_TREAT] [int] NOT NULL,
 CONSTRAINT [PK_MEDICAL_TREATMENT] PRIMARY KEY CLUSTERED 
(
	[ID_PAT_TREAT] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[MEDICAL_TREATMENT]  WITH CHECK ADD  CONSTRAINT [FK_MEDICAL_TREATMENT_PATIENT] FOREIGN KEY([PATIENT_ID])
REFERENCES [dbo].[PATIENT] ([ID_NUM])
GO

ALTER TABLE [dbo].[MEDICAL_TREATMENT] CHECK CONSTRAINT [FK_MEDICAL_TREATMENT_PATIENT]
GO

ALTER TABLE [dbo].[MEDICAL_TREATMENT]  WITH CHECK ADD  CONSTRAINT [FK_MEDICAL_TREATMENT_PROG_TREATMENT] FOREIGN KEY([TREAT_ID])
REFERENCES [dbo].[TREATMENT_PROG] ([TREAT_ID])
GO

ALTER TABLE [dbo].[MEDICAL_TREATMENT] CHECK CONSTRAINT [FK_MEDICAL_TREATMENT_PROG_TREATMENT]
GO

ALTER TABLE [dbo].[MEDICAL_TREATMENT]  WITH CHECK ADD  CONSTRAINT [CK_MEDICAL_TREATMENT_LAST_DOSE] CHECK  (([LAST_DOSE]<=CONVERT([date],getdate(),(0))))
GO

ALTER TABLE [dbo].[MEDICAL_TREATMENT] CHECK CONSTRAINT [CK_MEDICAL_TREATMENT_LAST_DOSE]
GO

ALTER TABLE [dbo].[MEDICAL_TREATMENT]  WITH CHECK ADD  CONSTRAINT [CK_MEDICAL_TREATMENT_NEXT_DOSE] CHECK  (([NEXT_DOSE]>[LAST_DOSE]))
GO

ALTER TABLE [dbo].[MEDICAL_TREATMENT] CHECK CONSTRAINT [CK_MEDICAL_TREATMENT_NEXT_DOSE]
GO

ALTER TABLE [dbo].[MEDICAL_TREATMENT]  WITH CHECK ADD  CONSTRAINT [CK_MEDICAL_TREATMENT_QUANTITY] CHECK  (([QUANTITY]>(0)))
GO

ALTER TABLE [dbo].[MEDICAL_TREATMENT] CHECK CONSTRAINT [CK_MEDICAL_TREATMENT_QUANTITY]
GO

ALTER TABLE [dbo].[MEDICAL_TREATMENT]  WITH CHECK ADD  CONSTRAINT [CK_MEDICAL_TREATMENT_START] CHECK  (([START_DATE]<=CONVERT([date],getdate(),(0))))
GO

ALTER TABLE [dbo].[MEDICAL_TREATMENT] CHECK CONSTRAINT [CK_MEDICAL_TREATMENT_START]
GO

