USE [dbdf]
GO

/****** Object:  Table [dbo].[PATIENT_IN_REHAB]    Script Date: 01/19/2012 15:42:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PATIENT_IN_REHAB](
	[PATIENT_ID] [varchar](10) NOT NULL,
	[REHAB_ID] [int] NOT NULL,
	[ID_PAT_REHAB] [int] NOT NULL,
	[START_DATE] [date] NOT NULL,
 CONSTRAINT [PK_PATIENT_IN_REHAB] PRIMARY KEY CLUSTERED 
(
	[ID_PAT_REHAB] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[PATIENT_IN_REHAB]  WITH CHECK ADD  CONSTRAINT [FK_PATIENT_IN_REHAB_PATIENT] FOREIGN KEY([PATIENT_ID])
REFERENCES [dbo].[PATIENT] ([ID_NUM])
GO

ALTER TABLE [dbo].[PATIENT_IN_REHAB] CHECK CONSTRAINT [FK_PATIENT_IN_REHAB_PATIENT]
GO

ALTER TABLE [dbo].[PATIENT_IN_REHAB]  WITH CHECK ADD  CONSTRAINT [FK_PATIENT_IN_REHAB_REHAB_PROG] FOREIGN KEY([REHAB_ID])
REFERENCES [dbo].[SOC_REHAB_PROG] ([REHAB_ID])
GO

ALTER TABLE [dbo].[PATIENT_IN_REHAB] CHECK CONSTRAINT [FK_PATIENT_IN_REHAB_REHAB_PROG]
GO

ALTER TABLE [dbo].[PATIENT_IN_REHAB] ADD  DEFAULT (CONVERT([date],getdate(),0)) FOR [START_DATE]
GO

