USE [dbdf]
GO

/****** Object:  Table [dbo].[PATIENT]    Script Date: 01/19/2012 15:42:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PATIENT](
	[ID_NUM] [varchar](10) NOT NULL,
	[AMKA] [bigint] NOT NULL,
	[BIRTH_DATE] [date] NOT NULL,
	[TREATMENT_COMPLETE] [bit] NOT NULL,
	[REHAB_COMPLETE] [bit] NOT NULL,
	[NAME_EMERG_CONTACT] [varchar](50) NULL,
	[TEL_EMERG_CONTACT] [numeric](14, 0) NULL,
	[RELATION_EMERG_CONTACT] [varchar](20) NULL,
	[ID] [char](10) NOT NULL,
 CONSTRAINT [PK_PATIENTS] PRIMARY KEY CLUSTERED 
(
	[ID_NUM] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[PATIENT]  WITH CHECK ADD  CONSTRAINT [FK_PATIENT_PERSON] FOREIGN KEY([ID])
REFERENCES [dbo].[PERSON] ([ID])
GO

ALTER TABLE [dbo].[PATIENT] CHECK CONSTRAINT [FK_PATIENT_PERSON]
GO

ALTER TABLE [dbo].[PATIENT]  WITH CHECK ADD  CONSTRAINT [CK_PATIENT_DATE] CHECK  (([BIRTH_DATE]<CONVERT([date],getdate(),(0))))
GO

ALTER TABLE [dbo].[PATIENT] CHECK CONSTRAINT [CK_PATIENT_DATE]
GO

