USE [dbdf]
GO

/****** Object:  Table [dbo].[SOC_REHAB_PROG]    Script Date: 01/19/2012 15:43:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SOC_REHAB_PROG](
	[REHAB_ID] [int] NOT NULL,
	[TITLE] [varchar](50) NOT NULL,
	[AVAIL_POSITIONS] [int] NOT NULL,
	[RESP_EMP] [varchar](10) NOT NULL,
	[CENTER_ID] [numeric](18, 0) NOT NULL,
 CONSTRAINT [PK_SOC_REHAB_PROG] PRIMARY KEY CLUSTERED 
(
	[REHAB_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SOC_REHAB_PROG]  WITH CHECK ADD  CONSTRAINT [FK_SOC_REHAB_PROG_CENTER] FOREIGN KEY([CENTER_ID])
REFERENCES [dbo].[CENTER] ([C_ID])
GO

ALTER TABLE [dbo].[SOC_REHAB_PROG] CHECK CONSTRAINT [FK_SOC_REHAB_PROG_CENTER]
GO

ALTER TABLE [dbo].[SOC_REHAB_PROG]  WITH CHECK ADD  CONSTRAINT [FK_SOC_REHAB_PROG_EMPLOYEE] FOREIGN KEY([RESP_EMP])
REFERENCES [dbo].[EMPLOYEE] ([ID_NUM])
GO

ALTER TABLE [dbo].[SOC_REHAB_PROG] CHECK CONSTRAINT [FK_SOC_REHAB_PROG_EMPLOYEE]
GO

ALTER TABLE [dbo].[SOC_REHAB_PROG]  WITH CHECK ADD  CONSTRAINT [CK_SOC_REHAB_PROG_POSITIONS] CHECK  (([AVAIL_POSITIONS]>(0)))
GO

ALTER TABLE [dbo].[SOC_REHAB_PROG] CHECK CONSTRAINT [CK_SOC_REHAB_PROG_POSITIONS]
GO

