USE [dbdf]
GO

/****** Object:  Table [dbo].[WAITING_LIST]    Script Date: 01/19/2012 15:45:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[WAITING_LIST](
	[WAIT_ID] [int] NOT NULL,
	[PATIENT_ID] [varchar](10) NOT NULL,
	[PROG_ID] [int] NOT NULL,
	[APPLY_DATE] [date] NOT NULL,
 CONSTRAINT [PK_WAITING_LIST] PRIMARY KEY CLUSTERED 
(
	[WAIT_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[WAITING_LIST]  WITH CHECK ADD  CONSTRAINT [FK_WAITING_LIST_PATIENT] FOREIGN KEY([PATIENT_ID])
REFERENCES [dbo].[PATIENT] ([ID_NUM])
GO

ALTER TABLE [dbo].[WAITING_LIST] CHECK CONSTRAINT [FK_WAITING_LIST_PATIENT]
GO

ALTER TABLE [dbo].[WAITING_LIST]  WITH CHECK ADD  CONSTRAINT [FK_WAITING_LIST_TREAT_PROG] FOREIGN KEY([PROG_ID])
REFERENCES [dbo].[TREATMENT_PROG] ([TREAT_ID])
GO

ALTER TABLE [dbo].[WAITING_LIST] CHECK CONSTRAINT [FK_WAITING_LIST_TREAT_PROG]
GO

ALTER TABLE [dbo].[WAITING_LIST] ADD  DEFAULT (CONVERT([date],getdate(),0)) FOR [APPLY_DATE]
GO

